name: Continuous Integration
on:
 pull_request:
   branches: [master]
 push:
   branches: [master]
jobs:
  rewrites:
    name: Test Rewrites
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - name: Rewrites 3.0
        run: sbt 'set rewrites / migration := "3.0"; rewrites / test'
      - name: Rewrites 3.1
        run: sbt 'set rewrites / migration := "3.1"; rewrites / test'
      - name: Rewrites 3.1 Deprecation
        run: sbt 'set rewrites / migration := "3.1-deprecation"; rewrites / test'
  incompat:
    name: Test Incompatibilities
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
      - name: Test Incompatibilities
        run: sbt '++0.26.0-RC1; incompat / test; ++2.13.3; incompat / test'
